FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install ts-node globally and then install project dependencies
RUN npm install -g ts-node typescript
RUN npm install

EXPOSE 4000

CMD ["npm", "run", "dev"] 